/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteRouteImport } from './routes/auth/sign-up/route'
import { Route as AuthSignInRouteRouteImport } from './routes/auth/sign-in/route'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignOutIndexRouteImport } from './routes/auth/sign-out/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthSignUpVerifyIndexRouteImport } from './routes/auth/sign-up/verify/index'
import { Route as AuthenticatedDashboardUserIndexRouteImport } from './routes/_authenticated/dashboard/user/index'
import { Route as AuthenticatedDashboardTransactionsIndexRouteImport } from './routes/_authenticated/dashboard/transactions/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRouteRoute = AuthSignUpRouteRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRouteRoute = AuthSignInRouteRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignUpRouteRoute,
} as any)
const AuthSignOutIndexRoute = AuthSignOutIndexRouteImport.update({
  id: '/auth/sign-out/',
  path: '/auth/sign-out/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthSignUpVerifyIndexRoute = AuthSignUpVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => AuthSignUpRouteRoute,
} as any)
const AuthenticatedDashboardUserIndexRoute =
  AuthenticatedDashboardUserIndexRouteImport.update({
    id: '/dashboard/user/',
    path: '/dashboard/user/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTransactionsIndexRoute =
  AuthenticatedDashboardTransactionsIndexRouteImport.update({
    id: '/dashboard/transactions/',
    path: '/dashboard/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRouteRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-out': typeof AuthSignOutIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsIndexRoute
  '/dashboard/user': typeof AuthenticatedDashboardUserIndexRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-out': typeof AuthSignOutIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsIndexRoute
  '/dashboard/user': typeof AuthenticatedDashboardUserIndexRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRouteRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-out/': typeof AuthSignOutIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_authenticated/dashboard/transactions/': typeof AuthenticatedDashboardTransactionsIndexRoute
  '/_authenticated/dashboard/user/': typeof AuthenticatedDashboardUserIndexRoute
  '/auth/sign-up/verify/': typeof AuthSignUpVerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard'
    | '/auth/sign-in/'
    | '/auth/sign-out'
    | '/auth/sign-up/'
    | '/dashboard/transactions'
    | '/dashboard/user'
    | '/auth/sign-up/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/dashboard/transactions'
    | '/dashboard/user'
    | '/auth/sign-up/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authenticated/dashboard/'
    | '/auth/sign-in/'
    | '/auth/sign-out/'
    | '/auth/sign-up/'
    | '/_authenticated/dashboard/transactions/'
    | '/_authenticated/dashboard/user/'
    | '/auth/sign-up/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthSignInRouteRoute: typeof AuthSignInRouteRouteWithChildren
  AuthSignUpRouteRoute: typeof AuthSignUpRouteRouteWithChildren
  AuthSignOutIndexRoute: typeof AuthSignOutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthSignUpRouteRoute
    }
    '/auth/sign-out/': {
      id: '/auth/sign-out/'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/sign-up/verify/': {
      id: '/auth/sign-up/verify/'
      path: '/verify'
      fullPath: '/auth/sign-up/verify'
      preLoaderRoute: typeof AuthSignUpVerifyIndexRouteImport
      parentRoute: typeof AuthSignUpRouteRoute
    }
    '/_authenticated/dashboard/user/': {
      id: '/_authenticated/dashboard/user/'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof AuthenticatedDashboardUserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/transactions/': {
      id: '/_authenticated/dashboard/transactions/'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardTransactionsIndexRoute: typeof AuthenticatedDashboardTransactionsIndexRoute
  AuthenticatedDashboardUserIndexRoute: typeof AuthenticatedDashboardUserIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardTransactionsIndexRoute:
    AuthenticatedDashboardTransactionsIndexRoute,
  AuthenticatedDashboardUserIndexRoute: AuthenticatedDashboardUserIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthSignInRouteRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInRouteRouteChildren: AuthSignInRouteRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInRouteRouteWithChildren = AuthSignInRouteRoute._addFileChildren(
  AuthSignInRouteRouteChildren,
)

interface AuthSignUpRouteRouteChildren {
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  AuthSignUpVerifyIndexRoute: typeof AuthSignUpVerifyIndexRoute
}

const AuthSignUpRouteRouteChildren: AuthSignUpRouteRouteChildren = {
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  AuthSignUpVerifyIndexRoute: AuthSignUpVerifyIndexRoute,
}

const AuthSignUpRouteRouteWithChildren = AuthSignUpRouteRoute._addFileChildren(
  AuthSignUpRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthSignInRouteRoute: AuthSignInRouteRouteWithChildren,
  AuthSignUpRouteRoute: AuthSignUpRouteRouteWithChildren,
  AuthSignOutIndexRoute: AuthSignOutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
